telegram:
  bot:
    name : RepeatIt_tgbot
    token: 7747921479:AAHnTGPmT3Wx6iretMBuK5k65lArPc5SX1o

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: repeat_it