SET search_path TO repeat_it;
ALTER TABLE card
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'READY';
ALTER TABLE card
    ADD CHECK (status IN ('DRAFT','READY','EDITING_FRONT_SIDE','EDITING_BACK_SIDE','DELETED'));