services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../src/main/resources/db_init:/docker-entrypoint-initdb.d  # Монтируем скрипты инициализации
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: